package io.github.uxlabspk.organote.ui.theme

import androidx.compose.ui.graphics.Color

// Light Mode Colors
val SurfaceLight = Color(0xFFF8F9FD)
val SurfaceDimLight = Color(0xFFD8DADE)
val SurfaceBrightLight = Color(0xFFF8F9FD)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF2F3F7)
val SurfaceContainerLight = Color(0xFFECEEF2)
val SurfaceContainerHighLight = Color(0xFFE7E8EC)
val SurfaceContainerHighestLight = Color(0xFFE1E2E6)
val OnSurfaceLight = Color(0xFF191C1F)
val OnSurfaceVariantLight = Color(0xFF41484E)
val InverseSurfaceLight = Color(0xFF2E3134)
val InverseOnSurfaceLight = Color(0xFFEFF1F5)
val OutlineLight = Color(0xFF71787F)
val OutlineVariantLight = Color(0xFFC0C7CF)
val SurfaceTintLight = Color(0xFF1C648E)
val PrimaryLight = Color(0xFF1C648E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF7CB9E8)
val OnPrimaryContainerLight = Color(0xFF00496D)
val InversePrimaryLight = Color(0xFF90CDFD)
val SecondaryLight = Color(0xFF35693C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFB4EEB4)
val OnSecondaryContainerLight = Color(0xFF3A6E3F)
val TertiaryLight = Color(0xFF5C5D6E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFB1B1C4)
val OnTertiaryContainerLight = Color(0xFF424453)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)
val PrimaryFixedLight = Color(0xFFCAE6FF)
val PrimaryFixedDimLight = Color(0xFF90CDFD)
val OnPrimaryFixedLight = Color(0xFF001E30)
val OnPrimaryFixedVariantLight = Color(0xFF004B70)
val SecondaryFixedLight = Color(0xFFB7F1B7)
val SecondaryFixedDimLight = Color(0xFF9CD49C)
val OnSecondaryFixedLight = Color(0xFF002107)
val OnSecondaryFixedVariantLight = Color(0xFF1C5126)
val TertiaryFixedLight = Color(0xFFE1E1F5)
val TertiaryFixedDimLight = Color(0xFFC5C5D8)
val OnTertiaryFixedLight = Color(0xFF191B29)
val OnTertiaryFixedVariantLight = Color(0xFF444655)
val BackgroundLight = Color(0xFFF8F9FD)
val OnBackgroundLight = Color(0xFF191C1F)
val SurfaceVariantLight = Color(0xFFE1E2E6)

// Dark Mode Colors (Deep Charcoal based on description)
// Since explicit dark mode hex codes aren't provided, I'll use standard dark translations or sensible defaults 
// that avoid pure black as requested.
val BackgroundDark = Color(0xFF191C1F) // Deep Charcoal
val SurfaceDark = Color(0xFF191C1F)
val OnSurfaceDark = Color(0xFFE1E2E6)
val PrimaryDark = Color(0xFF90CDFD)
val OnPrimaryDark = Color(0xFF00344F)
val SecondaryDark = Color(0xFF9CD49C)
val OnSecondaryDark = Color(0xFF003910)
val TertiaryDark = Color(0xFFC5C5D8)
val OnTertiaryDark = Color(0xFF2E2F3F)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val SurfaceVariantDark = Color(0xFF41484E)
val OnSurfaceVariantDark = Color(0xFFC0C7CF)
val OutlineDark = Color(0xFF8B9199)
